// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor_id, action, target, metadata) VALUES ($1, $2, $3, $4)
`

type InsertAuditLogParams struct {
	ActorID  *uuid.UUID
	Action   string
	Target   string
	Metadata []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Target,
		arg.Metadata,
	)
	return err
}
