// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createHold = `-- name: CreateHold :one
INSERT INTO holds (event_id, user_id, expires_at) VALUES ($1, $2, $3) RETURNING id, event_id, user_id, expires_at, status, created_at
`

type CreateHoldParams struct {
	EventID   uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateHold(ctx context.Context, arg CreateHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, createHold, arg.EventID, arg.UserID, arg.ExpiresAt)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, event_id, hold_id, total_cents, status, idempotency_key)
VALUES ($1, $2, $3, $4, 'pending_payment', $5) RETURNING id, user_id, event_id, hold_id, total_cents, status, idempotency_key, created_at, updated_at
`

type CreateOrderParams struct {
	UserID         uuid.UUID
	EventID        uuid.UUID
	HoldID         uuid.UUID
	TotalCents     int32
	IdempotencyKey string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.EventID,
		arg.HoldID,
		arg.TotalCents,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.HoldID,
		&i.TotalCents,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (order_id, kind, provider_ref, amount_cents, status, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (idempotency_key) DO NOTHING
`

type CreatePaymentParams struct {
	OrderID        uuid.UUID
	Kind           string
	ProviderRef    *string
	AmountCents    int32
	Status         string
	IdempotencyKey string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.Exec(ctx, createPayment,
		arg.OrderID,
		arg.Kind,
		arg.ProviderRef,
		arg.AmountCents,
		arg.Status,
		arg.IdempotencyKey,
	)
	return err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (id, order_id, event_seat_id, qr_token) VALUES ($1, $2, $3, $4) RETURNING id, order_id, event_seat_id, status, qr_token, created_at
`

type CreateTicketParams struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	EventSeatID uuid.UUID
	QrToken     string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ID,
		arg.OrderID,
		arg.EventSeatID,
		arg.QrToken,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EventSeatID,
		&i.Status,
		&i.QrToken,
		&i.CreatedAt,
	)
	return i, err
}

const expireHolds = `-- name: ExpireHolds :exec
UPDATE holds SET status = 'expired' WHERE id = ANY($1::uuid[])
`

func (q *Queries) ExpireHolds(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireHolds, ids)
	return err
}

const getChargeRef = `-- name: GetChargeRef :one
SELECT provider_ref FROM payments WHERE order_id = $1 AND kind = 'charge' AND status = 'succeeded'
`

func (q *Queries) GetChargeRef(ctx context.Context, orderID uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getChargeRef, orderID)
	var provider_ref *string
	err := row.Scan(&provider_ref)
	return provider_ref, err
}

const getHoldForUpdate = `-- name: GetHoldForUpdate :one
SELECT id, event_id, user_id, expires_at, status, created_at FROM holds WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetHoldForUpdate(ctx context.Context, id uuid.UUID) (Hold, error) {
	row := q.db.QueryRow(ctx, getHoldForUpdate, id)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, event_id, hold_id, total_cents, status, idempotency_key, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.HoldID,
		&i.TotalCents,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByKey = `-- name: GetOrderByKey :one
SELECT id, user_id, event_id, hold_id, total_cents, status, idempotency_key, created_at, updated_at FROM orders WHERE user_id = $1 AND idempotency_key = $2
`

type GetOrderByKeyParams struct {
	UserID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetOrderByKey(ctx context.Context, arg GetOrderByKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByKey, arg.UserID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.HoldID,
		&i.TotalCents,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, user_id, event_id, hold_id, total_cents, status, idempotency_key, created_at, updated_at FROM orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.HoldID,
		&i.TotalCents,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPendingOrderForHold = `-- name: HasPendingOrderForHold :one
SELECT EXISTS (SELECT 1 FROM orders WHERE hold_id = $1 AND status = 'pending_payment')
`

func (q *Queries) HasPendingOrderForHold(ctx context.Context, holdID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingOrderForHold, holdID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const holdSeats = `-- name: HoldSeats :execrows
UPDATE event_seats SET state = 'held', hold_id = $1::uuid, version = version + 1
WHERE id = ANY($2::uuid[]) AND state = 'available'
`

type HoldSeatsParams struct {
	HoldID  uuid.UUID
	SeatIds []uuid.UUID
}

func (q *Queries) HoldSeats(ctx context.Context, arg HoldSeatsParams) (int64, error) {
	result, err := q.db.Exec(ctx, holdSeats, arg.HoldID, arg.SeatIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listHoldSeats = `-- name: ListHoldSeats :many
SELECT id, price_cents FROM event_seats WHERE hold_id = $1 ORDER BY id
`

type ListHoldSeatsRow struct {
	ID         uuid.UUID
	PriceCents int32
}

func (q *Queries) ListHoldSeats(ctx context.Context, holdID *uuid.UUID) ([]ListHoldSeatsRow, error) {
	rows, err := q.db.Query(ctx, listHoldSeats, holdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldSeatsRow
	for rows.Next() {
		var i ListHoldSeatsRow
		if err := rows.Scan(&i.ID, &i.PriceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, event_id, hold_id, total_cents, status, idempotency_key, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.HoldID,
			&i.TotalCents,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByOrders = `-- name: ListTicketsByOrders :many
SELECT id, order_id, event_seat_id, status, qr_token, created_at FROM tickets WHERE order_id = ANY($1::uuid[]) ORDER BY created_at, id
`

func (q *Queries) ListTicketsByOrders(ctx context.Context, orderIds []uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByOrders, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.EventSeatID,
			&i.Status,
			&i.QrToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAvailableSeats = `-- name: LockAvailableSeats :many
SELECT id FROM event_seats
WHERE event_id = $1::uuid AND id = ANY($2::uuid[]) AND state = 'available'
ORDER BY id
FOR UPDATE SKIP LOCKED
`

type LockAvailableSeatsParams struct {
	EventID uuid.UUID
	SeatIds []uuid.UUID
}

// SKIP LOCKED: a seat another transaction is claiming right now counts as
// unavailable instead of making us wait for a lock we'd almost certainly lose.
// ORDER BY id gives every transaction the same lock order.
func (q *Queries) LockAvailableSeats(ctx context.Context, arg LockAvailableSeatsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockAvailableSeats, arg.EventID, arg.SeatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpiredHolds = `-- name: LockExpiredHolds :many
SELECT h.id FROM holds h
WHERE h.status = 'active' AND h.expires_at < now()
  AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.hold_id = h.id AND o.status = 'pending_payment')
ORDER BY h.expires_at
LIMIT $1::int
FOR UPDATE SKIP LOCKED
`

// Holds with a payment in flight are skipped: the buyer may already have been
// charged, so their seats must not be released under them.
func (q *Queries) LockExpiredHolds(ctx context.Context, batch int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockExpiredHolds, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseHoldSeats = `-- name: ReleaseHoldSeats :execrows
UPDATE event_seats SET state = 'available', hold_id = NULL, version = version + 1
WHERE hold_id = $1 AND state = 'held'
`

func (q *Queries) ReleaseHoldSeats(ctx context.Context, holdID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseHoldSeats, holdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseOrderSeats = `-- name: ReleaseOrderSeats :execrows
UPDATE event_seats SET state = 'available', order_id = NULL, version = version + 1
WHERE order_id = $1 AND state = 'sold'
`

func (q *Queries) ReleaseOrderSeats(ctx context.Context, orderID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseOrderSeats, orderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseSeatsOfHolds = `-- name: ReleaseSeatsOfHolds :execrows
UPDATE event_seats SET state = 'available', hold_id = NULL, version = version + 1
WHERE hold_id = ANY($1::uuid[]) AND state = 'held'
`

func (q *Queries) ReleaseSeatsOfHolds(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseSeatsOfHolds, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sellHoldSeats = `-- name: SellHoldSeats :execrows
UPDATE event_seats SET state = 'sold', hold_id = NULL, order_id = $1::uuid, version = version + 1
WHERE hold_id = $2::uuid AND state = 'held'
`

type SellHoldSeatsParams struct {
	OrderID uuid.UUID
	HoldID  uuid.UUID
}

func (q *Queries) SellHoldSeats(ctx context.Context, arg SellHoldSeatsParams) (int64, error) {
	result, err := q.db.Exec(ctx, sellHoldSeats, arg.OrderID, arg.HoldID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setHoldStatus = `-- name: SetHoldStatus :exec
UPDATE holds SET status = $2 WHERE id = $1
`

type SetHoldStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetHoldStatus(ctx context.Context, arg SetHoldStatusParams) error {
	_, err := q.db.Exec(ctx, setHoldStatus, arg.ID, arg.Status)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE orders SET status = $2, updated_at = now() WHERE id = $1
`

type SetOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.ID, arg.Status)
	return err
}

const voidOrderTickets = `-- name: VoidOrderTickets :exec
UPDATE tickets SET status = 'void' WHERE order_id = $1 AND status = 'valid'
`

func (q *Queries) VoidOrderTickets(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, voidOrderTickets, orderID)
	return err
}
