// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateSeats implements pgx.CopyFromSource.
type iteratorForCreateSeats struct {
	rows                 []CreateSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SectionID,
		r.rows[0].RowLabel,
		r.rows[0].SeatNumber,
	}, nil
}

func (r iteratorForCreateSeats) Err() error {
	return nil
}

// Bulk insert through the Postgres COPY protocol: one round trip for thousands of seats.
func (q *Queries) CreateSeats(ctx context.Context, arg []CreateSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"seats"}, []string{"section_id", "row_label", "seat_number"}, &iteratorForCreateSeats{rows: arg})
}
