// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
INSERT INTO idempotency_keys (user_id, key, request_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, key) DO NOTHING
`

type ClaimIdempotencyKeyParams struct {
	UserID      uuid.UUID
	Key         string
	RequestHash string
	ExpiresAt   time.Time
}

// Inserting first is what makes concurrent retries safe: only one request can
// create the row, so only one runs the handler.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type DeleteIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, arg.UserID, arg.Key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, key, request_hash, response_status, response_body, created_at, expires_at FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const saveIdempotentResponse = `-- name: SaveIdempotentResponse :exec
UPDATE idempotency_keys SET response_status = $3, response_body = $4 WHERE user_id = $1 AND key = $2
`

type SaveIdempotentResponseParams struct {
	UserID         uuid.UUID
	Key            string
	ResponseStatus *int32
	ResponseBody   []byte
}

func (q *Queries) SaveIdempotentResponse(ctx context.Context, arg SaveIdempotentResponseParams) error {
	_, err := q.db.Exec(ctx, saveIdempotentResponse,
		arg.UserID,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const takeOverIdempotencyKey = `-- name: TakeOverIdempotencyKey :execrows
UPDATE idempotency_keys SET created_at = now()
WHERE user_id = $1 AND key = $2 AND response_status IS NULL AND created_at < $3::timestamptz
`

type TakeOverIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    string
	Cutoff time.Time
}

// An in-progress row older than the cutoff belongs to a request that died; let the
// retry claim it. Only one retry can win the conditional update.
func (q *Queries) TakeOverIdempotencyKey(ctx context.Context, arg TakeOverIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, takeOverIdempotencyKey, arg.UserID, arg.Key, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
