// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAvailableSeats = `-- name: CountAvailableSeats :one
SELECT count(*) FROM event_seats WHERE event_id = $1 AND state = 'available'
`

func (q *Queries) CountAvailableSeats(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableSeats, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (venue_id, name, starts_at, on_sale_at, queue_enabled, admit_batch, admit_interval_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, venue_id, name, starts_at, on_sale_at, status, created_at, queue_enabled, admit_batch, admit_interval_seconds
`

type CreateEventParams struct {
	VenueID              uuid.UUID
	Name                 string
	StartsAt             time.Time
	OnSaleAt             time.Time
	QueueEnabled         bool
	AdmitBatch           int32
	AdmitIntervalSeconds int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.VenueID,
		arg.Name,
		arg.StartsAt,
		arg.OnSaleAt,
		arg.QueueEnabled,
		arg.AdmitBatch,
		arg.AdmitIntervalSeconds,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.StartsAt,
		&i.OnSaleAt,
		&i.Status,
		&i.CreatedAt,
		&i.QueueEnabled,
		&i.AdmitBatch,
		&i.AdmitIntervalSeconds,
	)
	return i, err
}

const createEventSeatsForSection = `-- name: CreateEventSeatsForSection :execrows
INSERT INTO event_seats (event_id, seat_id, price_cents)
SELECT $1::uuid, s.id, $2::int
FROM seats s WHERE s.section_id = $3::uuid
`

type CreateEventSeatsForSectionParams struct {
	EventID    uuid.UUID
	PriceCents int32
	SectionID  uuid.UUID
}

func (q *Queries) CreateEventSeatsForSection(ctx context.Context, arg CreateEventSeatsForSectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEventSeatsForSection, arg.EventID, arg.PriceCents, arg.SectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type CreateSeatsParams struct {
	SectionID  uuid.UUID
	RowLabel   string
	SeatNumber int32
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (venue_id, name) VALUES ($1, $2) RETURNING id, venue_id, name
`

type CreateSectionParams struct {
	VenueID uuid.UUID
	Name    string
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection, arg.VenueID, arg.Name)
	var i Section
	err := row.Scan(&i.ID, &i.VenueID, &i.Name)
	return i, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, timezone) VALUES ($1, $2) RETURNING id, name, timezone, created_at
`

type CreateVenueParams struct {
	Name     string
	Timezone string
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue, arg.Name, arg.Timezone)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, venue_id, name, starts_at, on_sale_at, status, created_at, queue_enabled, admit_batch, admit_interval_seconds FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.StartsAt,
		&i.OnSaleAt,
		&i.Status,
		&i.CreatedAt,
		&i.QueueEnabled,
		&i.AdmitBatch,
		&i.AdmitIntervalSeconds,
	)
	return i, err
}

const getSeatMap = `-- name: GetSeatMap :many
SELECT es.id AS event_seat_id, es.price_cents, es.state,
       s.row_label, s.seat_number, sec.id AS section_id, sec.name AS section_name
FROM event_seats es
JOIN seats s      ON s.id = es.seat_id
JOIN sections sec ON sec.id = s.section_id
WHERE es.event_id = $1
ORDER BY sec.name, sec.id, s.row_label, s.seat_number
`

type GetSeatMapRow struct {
	EventSeatID uuid.UUID
	PriceCents  int32
	State       string
	RowLabel    string
	SeatNumber  int32
	SectionID   uuid.UUID
	SectionName string
}

func (q *Queries) GetSeatMap(ctx context.Context, eventID uuid.UUID) ([]GetSeatMapRow, error) {
	rows, err := q.db.Query(ctx, getSeatMap, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeatMapRow
	for rows.Next() {
		var i GetSeatMapRow
		if err := rows.Scan(
			&i.EventSeatID,
			&i.PriceCents,
			&i.State,
			&i.RowLabel,
			&i.SeatNumber,
			&i.SectionID,
			&i.SectionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, timezone, created_at FROM venues WHERE id = $1
`

func (q *Queries) GetVenue(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listOnSaleEventIDs = `-- name: ListOnSaleEventIDs :many
SELECT id FROM events WHERE status = 'on_sale' AND starts_at > now()
`

func (q *Queries) ListOnSaleEventIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOnSaleEventIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEvents = `-- name: ListPublicEvents :many
SELECT id, venue_id, name, starts_at, on_sale_at, status, created_at, queue_enabled, admit_batch, admit_interval_seconds FROM events
WHERE status <> 'draft'
  AND (starts_at, id) > ($1::timestamptz, $2::uuid)
ORDER BY starts_at, id
LIMIT $3::int
`

type ListPublicEventsParams struct {
	AfterStartsAt time.Time
	AfterID       uuid.UUID
	PageSize      int32
}

// Keyset pagination: cheaper than OFFSET and stable while new events are added.
func (q *Queries) ListPublicEvents(ctx context.Context, arg ListPublicEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPublicEvents, arg.AfterStartsAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.Name,
			&i.StartsAt,
			&i.OnSaleAt,
			&i.Status,
			&i.CreatedAt,
			&i.QueueEnabled,
			&i.AdmitBatch,
			&i.AdmitIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedOnSaleEvents = `-- name: ListQueuedOnSaleEvents :many
SELECT id, admit_batch, admit_interval_seconds FROM events
WHERE status = 'on_sale' AND queue_enabled AND on_sale_at <= now() AND starts_at > now()
`

type ListQueuedOnSaleEventsRow struct {
	ID                   uuid.UUID
	AdmitBatch           int32
	AdmitIntervalSeconds int32
}

func (q *Queries) ListQueuedOnSaleEvents(ctx context.Context) ([]ListQueuedOnSaleEventsRow, error) {
	rows, err := q.db.Query(ctx, listQueuedOnSaleEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueuedOnSaleEventsRow
	for rows.Next() {
		var i ListQueuedOnSaleEventsRow
		if err := rows.Scan(&i.ID, &i.AdmitBatch, &i.AdmitIntervalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByVenue = `-- name: ListSectionsByVenue :many
SELECT id, venue_id, name FROM sections WHERE venue_id = $1 ORDER BY name
`

func (q *Queries) ListSectionsByVenue(ctx context.Context, venueID uuid.UUID) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSectionsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(&i.ID, &i.VenueID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEvent = `-- name: PublishEvent :one
UPDATE events SET status = 'on_sale' WHERE id = $1 AND status = 'draft' RETURNING id, venue_id, name, starts_at, on_sale_at, status, created_at, queue_enabled, admit_batch, admit_interval_seconds
`

func (q *Queries) PublishEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, publishEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.StartsAt,
		&i.OnSaleAt,
		&i.Status,
		&i.CreatedAt,
		&i.QueueEnabled,
		&i.AdmitBatch,
		&i.AdmitIntervalSeconds,
	)
	return i, err
}
