// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID        int64
	ActorID   *uuid.UUID
	Action    string
	Target    string
	Metadata  []byte
	CreatedAt time.Time
}

type Event struct {
	ID                   uuid.UUID
	VenueID              uuid.UUID
	Name                 string
	StartsAt             time.Time
	OnSaleAt             time.Time
	Status               string
	CreatedAt            time.Time
	QueueEnabled         bool
	AdmitBatch           int32
	AdmitIntervalSeconds int32
}

type EventSeat struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	SeatID     uuid.UUID
	PriceCents int32
	State      string
	HoldID     *uuid.UUID
	OrderID    *uuid.UUID
	Version    int32
}

type Hold struct {
	ID        uuid.UUID
	EventID   uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	Status    string
	CreatedAt time.Time
}

type IdempotencyKey struct {
	UserID         uuid.UUID
	Key            string
	RequestHash    string
	ResponseStatus *int32
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type Order struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	EventID        uuid.UUID
	HoldID         uuid.UUID
	TotalCents     int32
	Status         string
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Outbox struct {
	ID          int64
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	CreatedAt   time.Time
	PublishedAt *time.Time
}

type Payment struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	Kind           string
	ProviderRef    *string
	AmountCents    int32
	Status         string
	IdempotencyKey string
	CreatedAt      time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FamilyID   uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	CreatedAt  time.Time
}

type Seat struct {
	ID         uuid.UUID
	SectionID  uuid.UUID
	RowLabel   string
	SeatNumber int32
}

type Section struct {
	ID      uuid.UUID
	VenueID uuid.UUID
	Name    string
}

type Ticket struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	EventSeatID uuid.UUID
	Status      string
	QrToken     string
	CreatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
}

type Venue struct {
	ID        uuid.UUID
	Name      string
	Timezone  string
	CreatedAt time.Time
}
