// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID        int64
	ActorID   *uuid.UUID
	Action    string
	Target    string
	Metadata  []byte
	CreatedAt time.Time
}

type Event struct {
	ID        uuid.UUID
	VenueID   uuid.UUID
	Name      string
	StartsAt  time.Time
	OnSaleAt  time.Time
	Status    string
	CreatedAt time.Time
}

type EventSeat struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	SeatID     uuid.UUID
	PriceCents int32
	State      string
	HoldID     *uuid.UUID
	OrderID    *uuid.UUID
	Version    int32
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FamilyID   uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	CreatedAt  time.Time
}

type Seat struct {
	ID         uuid.UUID
	SectionID  uuid.UUID
	RowLabel   string
	SeatNumber int32
}

type Section struct {
	ID      uuid.UUID
	VenueID uuid.UUID
	Name    string
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
}

type Venue struct {
	ID        uuid.UUID
	Name      string
	Timezone  string
	CreatedAt time.Time
}
