// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimOutbox = `-- name: ClaimOutbox :many
SELECT id, aggregate_id, event_type, payload, created_at FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimOutboxRow struct {
	ID          int64
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	CreatedAt   time.Time
}

// SKIP LOCKED lets several relay replicas drain the outbox without sending the
// same row twice at the same time.
func (q *Queries) ClaimOutbox(ctx context.Context, limit int32) ([]ClaimOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxRow
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (aggregate_id, event_type, payload) VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

const listStalePendingOrders = `-- name: ListStalePendingOrders :many
SELECT id, user_id, event_id, hold_id, total_cents, status, idempotency_key, created_at, updated_at FROM orders WHERE status = 'pending_payment' AND updated_at < $1 ORDER BY updated_at LIMIT $2
`

type ListStalePendingOrdersParams struct {
	UpdatedAt time.Time
	Limit     int32
}

func (q *Queries) ListStalePendingOrders(ctx context.Context, arg ListStalePendingOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listStalePendingOrders, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.HoldID,
			&i.TotalCents,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnrefundedCancelledOrders = `-- name: ListUnrefundedCancelledOrders :many
SELECT id, user_id, event_id, hold_id, total_cents, status, idempotency_key, created_at, updated_at FROM orders WHERE status = 'cancelled' AND updated_at < $1 ORDER BY updated_at LIMIT $2
`

type ListUnrefundedCancelledOrdersParams struct {
	UpdatedAt time.Time
	Limit     int32
}

func (q *Queries) ListUnrefundedCancelledOrders(ctx context.Context, arg ListUnrefundedCancelledOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUnrefundedCancelledOrders, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.HoldID,
			&i.TotalCents,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}

const outboxLag = `-- name: OutboxLag :one
SELECT COALESCE(EXTRACT(EPOCH FROM now() - min(created_at)), 0)::float8 FROM outbox WHERE published_at IS NULL
`

// Age in seconds of the oldest unpublished event (0 when empty); alerting watches it.
func (q *Queries) OutboxLag(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, outboxLag)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
